CPPFLAGS += \
	-DIMG_ADDRESS=$(IMG_ADDRESS)	\
	-DIMG_SIZE=$(IMG_SIZE)		\
	-DOF_OFFSET=$(OF_OFFSET)	\
	-DOF_ADDRESS=$(OF_ADDRESS)	\
	-DMEM_BANK=$(MEM_BANK)	\
	-DMEM_SIZE=$(MEM_SIZE)	\
	-DIMAGE_NAME="\"$(IMAGE_NAME)\""	\
	-DCMDLINE="\"$(LINUX_KERNEL_ARG_STRING)\""	\
	-DTOP_OF_MEMORY=$(TOP_OF_MEMORY)	\
	-DMACH_TYPE=$(MACH_TYPE)

ASFLAGS += -DMACH_TYPE=$(MACH_TYPE)

ifeq ($(CONFIG_DEBUG_3RD_STAGE),y)
ASFLAGS += -DCONFIG_DEBUG_3RD_STAGE
CPPFLAGS += -DCONFIG_DEBUG_3RD_STAGE
endif

ifeq ($(CONFIG_UPLOAD_3RD_STAGE),y)
CPPFLAGS += -DCONFIG_UPLOAD_3RD_STAGE
ASFLAGS += -DCONFIG_UPLOAD_3RD_STAGE
#Below : just a place holder. Not actually used.
CPPFLAGS += -DJUMP_ADDR=0x00000000
ASFLAGS += -DJUMP_ADDR=0x00000000

else ifeq ($(CONFIG_ONLY_INTERNAL_RAM),y)
CPPFLAGS += -DCONFIG_ONLY_INTERNAL_RAM
ASFLAGS += -DCONFIG_ONLY_INTERNAL_RAM
CPPFLAGS += -DJUMP_ADDR=0x00000000
ASFLAGS += -DJUMP_ADDR=0x00000000

else
CPPFLAGS += -DJUMP_ADDR=$(JUMP_ADDR)
ASFLAGS += -DJUMP_ADDR=$(JUMP_ADDR)
endif

ifeq ($(CONFIG_EXTERNAL_RAM_TEST),y)
CPPFLAGS += -DCONFIG_EXTERNAL_RAM_TEST
ASFLAGS += -DCONFIG_EXTERNAL_RAM_TEST
endif

ifeq ($(CONFIG_DEBUG),y)
CPPFLAGS += -DCONFIG_DEBUG
endif

ifneq (x$(CONFIG_DEBUG_CONSOLE_BAUDRATE),x)
CPPFLAGS += -DCONFIG_DEBUG_CONSOLE_BAUDRATE=$(CONFIG_DEBUG_CONSOLE_BAUDRATE)
else
CPPFLAGS += -DCONFIG_DEBUG_CONSOLE_BAUDRATE=115200
endif

ifeq ($(CONFIG_NO_CONSOLE_OUTPUT),y)
CPPFLAGS += -DCONFIG_NO_CONSOLE_OUTPUT
endif

ifeq ($(CONFIG_HW_DISPLAY_BANNER),y)
BANNER:="$(CONFIG_HW_BANNER)"
CPPFLAGS += -DBANNER="$(BANNER)"
CPPFLAGS += -DCONFIG_HW_DISPLAY_BANNER
endif

ifeq ($(CONFIG_HW_INIT),y)
CPPFLAGS += -DCONFIG_HW_INIT
endif

ifeq ($(CONFIG_BEEAVE_WITH_DEBUG_LEDS),y)
CPPFLAGS +=-DCONFIG_BEEAVE_WITH_DEBUG_LEDS
endif

ifeq ($(CONFIG_BEEAVE_DEBUG_LEDS_ON),y)
CPPFLAGS +=-DCONFIG_BEEAVE_DEBUG_LEDS_ON
endif

ifeq ($(CONFIG_BEEAVE_DEBUG_LEDS_OFF),y)
CPPFLAGS +=-DCONFIG_BEEAVE_DEBUG_LEDS_OFF
endif

ifeq ($(CONFIG_OVERRIDE_CMDLINE),y)
CPPFLAGS += -DCONFIG_OVERRIDE_CMDLINE
endif

ifeq ($(CONFIG_CHECK_APPLICATION_LOAD),y)
CPPFLAGS +=-DCONFIG_CHECK_APPLICATION_LOAD
CPPFLAGS +=-DCONFIG_CHECK_APPLICATION_VALUE=$(CONFIG_CHECK_APPLICATION_VALUE)
CPPFLAGS +=-DCONFIG_CHECK_APPLICATION_VAL_ADDR_OFFSET=$(CONFIG_CHECK_APPLICATION_VAL_ADDR_OFFSET)
endif

ifeq ($(CONFIG_OVERRIDE_CMDLINE),y)
CPPFLAGS += -DCONFIG_OVERRIDE_CMDLINE
endif

ifeq ($(CONFIG_TEST_FIRMWARE_LOAD_LOOP),y)
CPPFLAGS += -DCONFIG_TEST_FIRMWARE_LOAD_LOOP
endif

ifeq ($(CONFIG_FIRMWARE_LOAD_VALIDATION),y)
CPPFLAGS += -DCONFIG_FIRMWARE_LOAD_VALIDATION
CPPFLAGS += -DCONFIG_FIRMWARE_LOAD_VALIDATION_BYTE=$(CONFIG_FIRMWARE_LOAD_VALIDATION_BYTE)
endif

ifeq ($(CONFIG_DUMP_APP_START_AREA),y)
CPPFLAGS += -DCONFIG_DUMP_APP_START_AREA
endif
