CPPFLAGS += -DCONFIG_SAMA5D2_PROD358D
ASFLAGS += -DCONFIG_SAMA5D2_PROD358D

BOARD_DRIVERS_SRC = $(TOPDIR)/board/$(BOARDNAME)/driver
BOARD_INC_PATH = $(TOPDIR)/board/$(BOARDNAME)/include

#Add the board's dedicated include directory.
CPPFLAGS += -I$(BOARD_INC_PATH)


#Add MMU support
COBJS-$(CONFIG_WITH_MMU) += $(BOARD_DRIVERS_SRC)/cp15.o
SOBJS-$(CONFIG_WITH_MMU) += $(BOARD_DRIVERS_SRC)/cp15_asm_gcc.o
COBJS-$(CONFIG_WITH_MMU) += $(BOARD_DRIVERS_SRC)/mmu.o
COBJS-$(CONFIG_WITH_MMU) += $(BOARD_DRIVERS_SRC)/board_memories.o

ifeq ($(CONFIG_WITH_MMU),y)
CPPFLAGS += -I$(BOARD_DRIVERS_SRC)
endif

#Add DMA support file
COBJS-$(CONFIG_DATAFLASH_LOAD_WITH_DMA) += $(BOARD_DRIVERS_SRC)/dma_dev.o
COBJS-$(CONFIG_DATAFLASH_LOAD_WITH_DMA) += $(BOARD_DRIVERS_SRC)/xdmad.o
COBJS-$(CONFIG_DATAFLASH_LOAD_WITH_DMA) += $(BOARD_DRIVERS_SRC)/at91_xdma.o


#Add the memory lowlevel init code according to the actual type : only LP-DDR1 !
COBJS-$(CONFIG_LPDDR1) += $(BOARD_DRIVERS_SRC)/lpddr1.o
COBJS-$(CONFIG_RAM_CHIP_W948D2) += $(BOARD_DRIVERS_SRC)/wd948d2.o
